### ISSUE TITLE
Windows 10 Mobile compatibility: it's really exists?

### ISSUE THREAD

**Issue by mediaexplorer74** [UnicordDev/UniSky#7]
Hi! In Readme you wrote:

"Requires Windows 10 build 15063 or later"

Maybe I don't understand something, but literally in all commits in the source code I didn't see 10.0.15063.0. There is 10.0.16299. Although in AppManifest.xml in the compiled appx bundles ("internals"), the minimum OS version is specified correctly: MinVersion="10.0.15063.0"... What does it mean? Could you please provide at least a couple of photos of UniSky launched on your winphone?

Best,
mediaexplorer
_Big Nokia Lumia phones fanboy_

**Comment by WamWooWam** [comment]
Please peep this gist https://gist.github.com/WamWooWam/e72e5137606f7c59ed657db6587cd5e8
